[project]
name = 'Decentralized-Reality-Forking-Governance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.reality-branch-proposal]
path = 'contracts/reality-branch-proposal.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
